import "./globals.css";
export const metadata = {
  title: "GeekyShows",
  description: "Generated by geekyshows",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
